# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # # Run tests every month
  # schedule:
  #   - cron: '0 0 1 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: registry.plmlab.math.cnrs.fr/pmarchand/sphinx-docker/sphinx

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout sphinx_computer_tools
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # to get tags

      - name: Check links
        run: |
          cd docs && make linkcheck

      - name: Nitpicky html build
        run: |
          cd docs && make html SPHINXOPTS="-n -W"
      
      - name: Latex build
        run: |
          cd docs && make latexpdf
          
